namespace QuizSystem.Application.DTOs.SchoolManagement;

public sealed class GradeLevelDto { public Guid Id { get; set; } public Guid InstitutionId { get; set; } public string Name { get; set; } = string.Empty; public int Order { get; set; } public bool IsActive { get; set; } }
public sealed class UpsertGradeLevelRequest { public string? Name { get; set; } public int Order { get; set; } public bool IsActive { get; set; } = true; }
public sealed class SubjectDto { public Guid Id { get; set; } public Guid InstitutionId { get; set; } public Guid GradeLevelId { get; set; } public string GradeLevelName { get; set; } = string.Empty; public string Name { get; set; } = string.Empty; public string Code { get; set; } = string.Empty; public bool IsActive { get; set; } }
public sealed class UpsertSubjectRequest { public Guid GradeLevelId { get; set; } public string? Name { get; set; } public string? Code { get; set; } public bool IsActive { get; set; } = true; }
public sealed class TeacherProfileDto { public Guid Id { get; set; } public Guid InstitutionId { get; set; } public Guid? UserId { get; set; } public string FullName { get; set; } = string.Empty; public string? PhoneNumber { get; set; } public string? Email { get; set; } public string TeacherCode { get; set; } = string.Empty; public bool IsActive { get; set; } public List<Guid> SubjectIds { get; set; } = new(); }
public sealed class UpsertTeacherProfileRequest { public Guid? UserId { get; set; } public string? FullName { get; set; } public string? PhoneNumber { get; set; } public string? Email { get; set; } public string? TeacherCode { get; set; } public bool IsActive { get; set; } = true; public List<Guid>? SubjectIds { get; set; } }
public sealed class AssignTeacherSubjectsRequest { public List<Guid> SubjectIds { get; set; } = new(); }
public sealed class ClassSectionDto { public Guid Id { get; set; } public Guid InstitutionId { get; set; } public Guid GradeLevelId { get; set; } public string GradeLevelName { get; set; } = string.Empty; public Guid SubjectId { get; set; } public string SubjectName { get; set; } = string.Empty; public Guid? TeacherProfileId { get; set; } public string? TeacherName { get; set; } public string Name { get; set; } = string.Empty; public string GenderType { get; set; } = "Mixed"; public string? AcademicYear { get; set; } public string? Term { get; set; } public int? Capacity { get; set; } public bool IsActive { get; set; } public int StudentsCount { get; set; } }
public sealed class UpsertClassSectionRequest { public Guid GradeLevelId { get; set; } public Guid SubjectId { get; set; } public Guid? TeacherProfileId { get; set; } public string? Name { get; set; } public string? GenderType { get; set; } public string? AcademicYear { get; set; } public string? Term { get; set; } public int? Capacity { get; set; } public bool IsActive { get; set; } = true; }
public sealed class SectionStudentDto { public Guid Id { get; set; } public Guid InstitutionId { get; set; } public Guid ClassSectionId { get; set; } public Guid StudentProfileId { get; set; } public string StudentName { get; set; } = string.Empty; public string StudentCode { get; set; } = string.Empty; public string? Grade { get; set; } public DateTime AssignedAtUtc { get; set; } public bool IsActive { get; set; } }
public sealed class AssignSectionStudentsRequest { public List<Guid> StudentProfileIds { get; set; } = new(); public bool ReplaceExisting { get; set; } = false; }
