using Microsoft.EntityFrameworkCore;
using QuizSystem.Application.Contracts.SchoolManagement;
using QuizSystem.Application.DTOs.SchoolManagement;
using QuizSystem.Domain.Entities;
using QuizSystem.Infrastructure.Persistence;

namespace QuizSystem.Infrastructure.Services.SchoolManagement;

public class SchoolManagementService : ISchoolManagementService
{
    private readonly AppDbContext _db;
    public SchoolManagementService(AppDbContext db) { _db = db; }

    public async Task<IReadOnlyList<GradeLevelDto>> GetGradeLevelsAsync(Guid institutionId, CancellationToken ct) => await _db.GradeLevels.AsNoTracking().Where(x => x.InstitutionId == institutionId).OrderBy(x => x.Order).ThenBy(x => x.Name).Select(x => new GradeLevelDto { Id = x.Id, InstitutionId = x.InstitutionId, Name = x.Name, Order = x.Order, IsActive = x.IsActive }).ToListAsync(ct);
    public async Task<GradeLevelDto> CreateGradeLevelAsync(Guid institutionId, UpsertGradeLevelRequest r, CancellationToken ct) { Req(r.Name, "اسم المرحلة مطلوب"); var e = new GradeLevel { Id = Guid.NewGuid(), InstitutionId = institutionId, Name = r.Name!.Trim(), Order = r.Order, IsActive = r.IsActive }; _db.GradeLevels.Add(e); await _db.SaveChangesAsync(ct); return await Grade(institutionId, e.Id, ct); }
    public async Task<GradeLevelDto> UpdateGradeLevelAsync(Guid institutionId, Guid id, UpsertGradeLevelRequest r, CancellationToken ct) { Req(r.Name, "اسم المرحلة مطلوب"); var e = await _db.GradeLevels.FirstOrDefaultAsync(x => x.Id == id && x.InstitutionId == institutionId, ct) ?? throw new KeyNotFoundException("المرحلة غير موجودة"); e.Name = r.Name!.Trim(); e.Order = r.Order; e.IsActive = r.IsActive; await _db.SaveChangesAsync(ct); return await Grade(institutionId, id, ct); }
    public async Task SetGradeLevelStatusAsync(Guid institutionId, Guid id, bool isActive, CancellationToken ct) { if (await _db.GradeLevels.Where(x => x.Id == id && x.InstitutionId == institutionId).ExecuteUpdateAsync(s => s.SetProperty(x => x.IsActive, isActive), ct) == 0) throw new KeyNotFoundException("المرحلة غير موجودة"); }
    public async Task DeleteGradeLevelAsync(Guid institutionId, Guid id, CancellationToken ct) { if (await _db.Subjects.AnyAsync(x => x.InstitutionId == institutionId && x.GradeLevelId == id, ct) || await _db.ClassSections.AnyAsync(x => x.InstitutionId == institutionId && x.GradeLevelId == id, ct)) throw new InvalidOperationException("لا يمكن حذف مرحلة مرتبطة"); var e = await _db.GradeLevels.FirstOrDefaultAsync(x => x.Id == id && x.InstitutionId == institutionId, ct) ?? throw new KeyNotFoundException("المرحلة غير موجودة"); _db.GradeLevels.Remove(e); await _db.SaveChangesAsync(ct); }

    public async Task<IReadOnlyList<SubjectDto>> GetSubjectsAsync(Guid institutionId, Guid? gradeLevelId, CancellationToken ct) { var q = _db.Subjects.AsNoTracking().Include(x => x.GradeLevel).Where(x => x.InstitutionId == institutionId); if (gradeLevelId.HasValue) q = q.Where(x => x.GradeLevelId == gradeLevelId); return await q.OrderBy(x => x.Name).Select(x => new SubjectDto { Id = x.Id, InstitutionId = x.InstitutionId, GradeLevelId = x.GradeLevelId, GradeLevelName = x.GradeLevel.Name, Name = x.Name, Code = x.Code, IsActive = x.IsActive }).ToListAsync(ct); }
    public async Task<SubjectDto> CreateSubjectAsync(Guid institutionId, UpsertSubjectRequest r, CancellationToken ct) { Req(r.Name,"اسم المقرر مطلوب"); Req(r.Code,"كود المقرر مطلوب"); await EnsureGrade(institutionId,r.GradeLevelId,ct); var e = new Subject { Id = Guid.NewGuid(), InstitutionId = institutionId, GradeLevelId = r.GradeLevelId, Name = r.Name!.Trim(), Code = Code(r.Code), IsActive = r.IsActive }; _db.Subjects.Add(e); await _db.SaveChangesAsync(ct); return await Subject(institutionId,e.Id,ct); }
    public async Task<SubjectDto> UpdateSubjectAsync(Guid institutionId, Guid id, UpsertSubjectRequest r, CancellationToken ct) { Req(r.Name,"اسم المقرر مطلوب"); Req(r.Code,"كود المقرر مطلوب"); await EnsureGrade(institutionId,r.GradeLevelId,ct); var e = await _db.Subjects.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct) ?? throw new KeyNotFoundException("المقرر غير موجود"); e.GradeLevelId=r.GradeLevelId; e.Name=r.Name!.Trim(); e.Code=Code(r.Code); e.IsActive=r.IsActive; await _db.SaveChangesAsync(ct); return await Subject(institutionId,id,ct); }
    public async Task SetSubjectStatusAsync(Guid institutionId, Guid id, bool isActive, CancellationToken ct) { if (await _db.Subjects.Where(x=>x.Id==id&&x.InstitutionId==institutionId).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.IsActive,isActive),ct)==0) throw new KeyNotFoundException("المقرر غير موجود"); }
    public async Task DeleteSubjectAsync(Guid institutionId, Guid id, CancellationToken ct) { if (await _db.ClassSections.AnyAsync(x=>x.InstitutionId==institutionId&&x.SubjectId==id,ct)) throw new InvalidOperationException("لا يمكن حذف مقرر مرتبط بشعب"); var e=await _db.Subjects.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)??throw new KeyNotFoundException("المقرر غير موجود"); _db.Subjects.Remove(e); await _db.SaveChangesAsync(ct); }

    public async Task<IReadOnlyList<TeacherProfileDto>> GetTeachersAsync(Guid institutionId, CancellationToken ct) => await _db.TeacherProfiles.AsNoTracking().Include(x=>x.TeacherSubjects).Where(x=>x.InstitutionId==institutionId).OrderBy(x=>x.FullName).Select(x=>new TeacherProfileDto{Id=x.Id,InstitutionId=x.InstitutionId,UserId=x.UserId,FullName=x.FullName,PhoneNumber=x.PhoneNumber,Email=x.Email,TeacherCode=x.TeacherCode,IsActive=x.IsActive,SubjectIds=x.TeacherSubjects.Where(t=>t.IsActive).Select(t=>t.SubjectId).ToList()}).ToListAsync(ct);
    public async Task<TeacherProfileDto> CreateTeacherAsync(Guid institutionId, UpsertTeacherProfileRequest r, CancellationToken ct) { Req(r.FullName,"اسم المعلم مطلوب"); Req(r.TeacherCode,"كود المعلم مطلوب"); var e=new TeacherProfile{Id=Guid.NewGuid(),InstitutionId=institutionId,UserId=r.UserId,FullName=r.FullName!.Trim(),PhoneNumber=r.PhoneNumber?.Trim(),Email=r.Email?.Trim(),TeacherCode=Code(r.TeacherCode),IsActive=r.IsActive}; _db.TeacherProfiles.Add(e); await _db.SaveChangesAsync(ct); if(r.SubjectIds is not null) await AssignTeacherSubjectsAsync(institutionId,e.Id,new AssignTeacherSubjectsRequest{SubjectIds=r.SubjectIds},ct); return await Teacher(institutionId,e.Id,ct); }
    public async Task<TeacherProfileDto> UpdateTeacherAsync(Guid institutionId, Guid id, UpsertTeacherProfileRequest r, CancellationToken ct) { Req(r.FullName,"اسم المعلم مطلوب"); Req(r.TeacherCode,"كود المعلم مطلوب"); var e=await _db.TeacherProfiles.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)??throw new KeyNotFoundException("المعلم غير موجود"); e.UserId=r.UserId; e.FullName=r.FullName!.Trim(); e.PhoneNumber=r.PhoneNumber?.Trim(); e.Email=r.Email?.Trim(); e.TeacherCode=Code(r.TeacherCode); e.IsActive=r.IsActive; await _db.SaveChangesAsync(ct); if(r.SubjectIds is not null) await AssignTeacherSubjectsAsync(institutionId,id,new AssignTeacherSubjectsRequest{SubjectIds=r.SubjectIds},ct); return await Teacher(institutionId,id,ct); }
    public async Task SetTeacherStatusAsync(Guid institutionId, Guid id, bool isActive, CancellationToken ct) { if(await _db.TeacherProfiles.Where(x=>x.Id==id&&x.InstitutionId==institutionId).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.IsActive,isActive),ct)==0) throw new KeyNotFoundException("المعلم غير موجود"); }
    public async Task DeleteTeacherAsync(Guid institutionId, Guid id, CancellationToken ct) { if(await _db.ClassSections.AnyAsync(x=>x.InstitutionId==institutionId&&x.TeacherProfileId==id,ct)) throw new InvalidOperationException("لا يمكن حذف معلم مرتبط بشعب"); var e=await _db.TeacherProfiles.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)??throw new KeyNotFoundException("المعلم غير موجود"); _db.TeacherProfiles.Remove(e); await _db.SaveChangesAsync(ct); }
    public async Task AssignTeacherSubjectsAsync(Guid institutionId, Guid id, AssignTeacherSubjectsRequest r, CancellationToken ct) { if(!await _db.TeacherProfiles.AnyAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)) throw new KeyNotFoundException("المعلم غير موجود"); var ids=(r.SubjectIds??new()).Distinct().ToList(); var valid=await _db.Subjects.Where(x=>x.InstitutionId==institutionId&&ids.Contains(x.Id)).Select(x=>x.Id).ToListAsync(ct); if(valid.Count!=ids.Count) throw new InvalidOperationException("مقرر خارج المؤسسة الحالية"); var old=await _db.TeacherSubjects.Where(x=>x.InstitutionId==institutionId&&x.TeacherProfileId==id).ToListAsync(ct); _db.TeacherSubjects.RemoveRange(old); foreach(var sid in valid) _db.TeacherSubjects.Add(new TeacherSubject{Id=Guid.NewGuid(),InstitutionId=institutionId,TeacherProfileId=id,SubjectId=sid,IsActive=true}); await _db.SaveChangesAsync(ct); }

    public async Task<IReadOnlyList<ClassSectionDto>> GetClassSectionsAsync(Guid institutionId, Guid? gradeLevelId, Guid? subjectId, Guid? teacherProfileId, CancellationToken ct) { var q=_db.ClassSections.AsNoTracking().Include(x=>x.GradeLevel).Include(x=>x.Subject).Include(x=>x.TeacherProfile).Include(x=>x.SectionStudents).Where(x=>x.InstitutionId==institutionId); if(gradeLevelId.HasValue) q=q.Where(x=>x.GradeLevelId==gradeLevelId); if(subjectId.HasValue) q=q.Where(x=>x.SubjectId==subjectId); if(teacherProfileId.HasValue) q=q.Where(x=>x.TeacherProfileId==teacherProfileId); return await q.OrderBy(x=>x.Name).Select(x=>new ClassSectionDto{Id=x.Id,InstitutionId=x.InstitutionId,GradeLevelId=x.GradeLevelId,GradeLevelName=x.GradeLevel.Name,SubjectId=x.SubjectId,SubjectName=x.Subject.Name,TeacherProfileId=x.TeacherProfileId,TeacherName=x.TeacherProfile==null?null:x.TeacherProfile.FullName,Name=x.Name,GenderType=x.GenderType,AcademicYear=x.AcademicYear,Term=x.Term,Capacity=x.Capacity,IsActive=x.IsActive,StudentsCount=x.SectionStudents.Count(s=>s.IsActive)}).ToListAsync(ct); }
    public async Task<ClassSectionDto> CreateClassSectionAsync(Guid institutionId, UpsertClassSectionRequest r, CancellationToken ct) { Req(r.Name,"اسم الشعبة مطلوب"); await EnsureGrade(institutionId,r.GradeLevelId,ct); await EnsureSubject(institutionId,r.SubjectId,ct); if(r.TeacherProfileId.HasValue) await EnsureTeacher(institutionId,r.TeacherProfileId.Value,ct); var e=new ClassSection{Id=Guid.NewGuid(),InstitutionId=institutionId,GradeLevelId=r.GradeLevelId,SubjectId=r.SubjectId,TeacherProfileId=r.TeacherProfileId,Name=r.Name!.Trim(),GenderType=string.IsNullOrWhiteSpace(r.GenderType)?"Mixed":r.GenderType.Trim(),AcademicYear=r.AcademicYear?.Trim(),Term=r.Term?.Trim(),Capacity=r.Capacity,IsActive=r.IsActive}; _db.ClassSections.Add(e); await _db.SaveChangesAsync(ct); return (await GetClassSectionsAsync(institutionId,null,null,null,ct)).First(x=>x.Id==e.Id); }
    public async Task<ClassSectionDto> UpdateClassSectionAsync(Guid institutionId, Guid id, UpsertClassSectionRequest r, CancellationToken ct) { Req(r.Name,"اسم الشعبة مطلوب"); await EnsureGrade(institutionId,r.GradeLevelId,ct); await EnsureSubject(institutionId,r.SubjectId,ct); if(r.TeacherProfileId.HasValue) await EnsureTeacher(institutionId,r.TeacherProfileId.Value,ct); var e=await _db.ClassSections.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)??throw new KeyNotFoundException("الشعبة غير موجودة"); e.GradeLevelId=r.GradeLevelId; e.SubjectId=r.SubjectId; e.TeacherProfileId=r.TeacherProfileId; e.Name=r.Name!.Trim(); e.GenderType=string.IsNullOrWhiteSpace(r.GenderType)?"Mixed":r.GenderType.Trim(); e.AcademicYear=r.AcademicYear?.Trim(); e.Term=r.Term?.Trim(); e.Capacity=r.Capacity; e.IsActive=r.IsActive; await _db.SaveChangesAsync(ct); return (await GetClassSectionsAsync(institutionId,null,null,null,ct)).First(x=>x.Id==id); }
    public async Task SetClassSectionStatusAsync(Guid institutionId, Guid id, bool isActive, CancellationToken ct) { if(await _db.ClassSections.Where(x=>x.Id==id&&x.InstitutionId==institutionId).ExecuteUpdateAsync(s=>s.SetProperty(x=>x.IsActive,isActive),ct)==0) throw new KeyNotFoundException("الشعبة غير موجودة"); }
    public async Task DeleteClassSectionAsync(Guid institutionId, Guid id, CancellationToken ct) { if(await _db.SectionStudents.AnyAsync(x=>x.InstitutionId==institutionId&&x.ClassSectionId==id,ct)) throw new InvalidOperationException("الشعبة تحتوي على طلاب"); var e=await _db.ClassSections.FirstOrDefaultAsync(x=>x.Id==id&&x.InstitutionId==institutionId,ct)??throw new KeyNotFoundException("الشعبة غير موجودة"); _db.ClassSections.Remove(e); await _db.SaveChangesAsync(ct); }

    public async Task<IReadOnlyList<SectionStudentDto>> GetSectionStudentsAsync(Guid institutionId, Guid classSectionId, CancellationToken ct) => await _db.SectionStudents.AsNoTracking().Include(x=>x.StudentProfile).Where(x=>x.InstitutionId==institutionId&&x.ClassSectionId==classSectionId).OrderBy(x=>x.StudentProfile.FullName).Select(x=>new SectionStudentDto{Id=x.Id,InstitutionId=x.InstitutionId,ClassSectionId=x.ClassSectionId,StudentProfileId=x.StudentProfileId,StudentName=x.StudentProfile.FullName,StudentCode=x.StudentProfile.StudentCode,Grade=x.StudentProfile.Grade,AssignedAtUtc=x.AssignedAtUtc,IsActive=x.IsActive}).ToListAsync(ct);
    public async Task AssignStudentsToSectionAsync(Guid institutionId, Guid classSectionId, AssignSectionStudentsRequest r, CancellationToken ct) { if(!await _db.ClassSections.AnyAsync(x=>x.Id==classSectionId&&x.InstitutionId==institutionId,ct)) throw new KeyNotFoundException("الشعبة غير موجودة"); var ids=(r.StudentProfileIds??new()).Distinct().ToList(); var valid=await _db.Students.Where(x=>x.InstitutionId==institutionId&&ids.Contains(x.Id)).Select(x=>x.Id).ToListAsync(ct); if(valid.Count!=ids.Count) throw new InvalidOperationException("طالب خارج المؤسسة الحالية"); var old=await _db.SectionStudents.Where(x=>x.InstitutionId==institutionId&&x.ClassSectionId==classSectionId).ToListAsync(ct); if(r.ReplaceExisting) _db.SectionStudents.RemoveRange(old.Where(x=>!valid.Contains(x.StudentProfileId))); foreach(var sid in valid){ var row=old.FirstOrDefault(x=>x.StudentProfileId==sid); if(row==null) _db.SectionStudents.Add(new SectionStudent{Id=Guid.NewGuid(),InstitutionId=institutionId,ClassSectionId=classSectionId,StudentProfileId=sid,AssignedAtUtc=DateTime.UtcNow,IsActive=true}); else {row.IsActive=true; row.AssignedAtUtc=DateTime.UtcNow;} } await _db.SaveChangesAsync(ct); }
    public async Task RemoveStudentFromSectionAsync(Guid institutionId, Guid classSectionId, Guid studentProfileId, CancellationToken ct) { var row=await _db.SectionStudents.FirstOrDefaultAsync(x=>x.InstitutionId==institutionId&&x.ClassSectionId==classSectionId&&x.StudentProfileId==studentProfileId,ct)??throw new KeyNotFoundException("الطالب غير مسجل في الشعبة"); _db.SectionStudents.Remove(row); await _db.SaveChangesAsync(ct); }

    private async Task<GradeLevelDto> Grade(Guid inst, Guid id, CancellationToken ct)=> (await GetGradeLevelsAsync(inst,ct)).First(x=>x.Id==id);
    private async Task<SubjectDto> Subject(Guid inst, Guid id, CancellationToken ct)=> (await GetSubjectsAsync(inst,null,ct)).First(x=>x.Id==id);
    private async Task<TeacherProfileDto> Teacher(Guid inst, Guid id, CancellationToken ct)=> (await GetTeachersAsync(inst,ct)).First(x=>x.Id==id);
    private async Task EnsureGrade(Guid inst, Guid id, CancellationToken ct){ if(id==Guid.Empty||!await _db.GradeLevels.AnyAsync(x=>x.Id==id&&x.InstitutionId==inst,ct)) throw new KeyNotFoundException("المرحلة غير موجودة"); }
    private async Task EnsureSubject(Guid inst, Guid id, CancellationToken ct){ if(id==Guid.Empty||!await _db.Subjects.AnyAsync(x=>x.Id==id&&x.InstitutionId==inst,ct)) throw new KeyNotFoundException("المقرر غير موجود"); }
    private async Task EnsureTeacher(Guid inst, Guid id, CancellationToken ct){ if(!await _db.TeacherProfiles.AnyAsync(x=>x.Id==id&&x.InstitutionId==inst,ct)) throw new KeyNotFoundException("المعلم غير موجود"); }
    private static void Req(string? v,string m){ if(string.IsNullOrWhiteSpace(v)) throw new ArgumentException(m); }
    private static string Code(string? v)=> string.IsNullOrWhiteSpace(v)?string.Empty:v.Trim().ToUpperInvariant();
}
