import { useEffect, useMemo, useState } from "react";
import { schoolApi } from "../../../services/schoolManagementApi";
import { getStudentLookups, getUsers, getCourseSupervisorAssignments, setCourseSupervisors } from "../../../services/api";
import "./schoolManagement.css";

const emptyGrade={name:"",order:1,isActive:true};
const emptySubject={gradeLevelId:"",name:"",code:"",isActive:true};
const emptyTeacher={userId:"",fullName:"",phoneNumber:"",email:"",teacherCode:"",isActive:true,subjectIds:[]};
const emptySection={gradeLevelId:"",subjectId:"",teacherProfileId:"",name:"",genderType:"Mixed",academicYear:"",term:"",capacity:"",isActive:true};
const tabs=[{key:"grades",label:"المراحل الدراسية",icon:"🎓"},{key:"subjects",label:"المقررات",icon:"📚"},{key:"teachers",label:"المعلمون",icon:"👨‍🏫"},{key:"sections",label:"الشعب الدراسية",icon:"🏫"},{key:"students",label:"تسجيل الطلاب",icon:"👥"}];
const arr=(v)=>Array.isArray(v)?v:[];
const byId=(list,id)=>arr(list).find(x=>String(x.id)===String(id));
const norm=(v)=>v||null;

function Modal({title,subtitle,children,onClose}){return <div className="school-modal-backdrop" onClick={onClose}><div className="school-modal" onClick={e=>e.stopPropagation()}><div className="school-modal-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="school-btn soft" onClick={onClose}>إغلاق</button></div>{children}</div></div>}
function Field({label,children}){return <div className="school-form-field"><label>{label}</label>{children}</div>}
function ActiveField({form,setForm}){return <div className="school-form-field"><label>الحالة</label><label className="school-check-row"><input type="checkbox" checked={form.isActive!==false} onChange={e=>setForm({...form,isActive:e.target.checked})}/> نشط</label></div>}
function SaveActions({mode,onClose}){return <div className="school-form-field full"><div className="school-card-actions"><button className="school-btn primary" type="submit">{mode==="edit"?"حفظ التعديل":"إضافة"}</button><button className="school-btn soft" type="button" onClick={onClose}>إلغاء</button></div></div>}
function Grid({rows,empty,render}){return !rows.length?<div className="school-empty">{empty}</div>:<div className="school-grid">{rows.map(render)}</div>}
function Actions({onEdit,onStatus,onDelete,extra}){return <div className="school-card-actions">{extra}<button className="school-btn secondary" onClick={onEdit}>تعديل</button><button className="school-btn soft" onClick={onStatus}>تفعيل/تعطيل</button><button className="school-btn danger" onClick={onDelete}>حذف</button></div>}

export default function SchoolManagementPage(){
 const [activeTab,setActiveTab]=useState("grades");
 const [grades,setGrades]=useState([]),[subjects,setSubjects]=useState([]),[teachers,setTeachers]=useState([]),[sections,setSections]=useState([]),[students,setStudents]=useState([]),[users,setUsers]=useState([]);
 const [supervisorData,setSupervisorData]=useState({supervisors:[],assignments:[]});
 const [search,setSearch]=useState(""),[error,setError]=useState(""),[success,setSuccess]=useState(""),[loading,setLoading]=useState(false),[modal,setModal]=useState(null);
 const [selectedSection,setSelectedSection]=useState(""),[sectionStudents,setSectionStudents]=useState([]),[studentSelection,setStudentSelection]=useState([]);
 async function loadAll(){try{setLoading(true);setError("");const [g,s,t,c,st,u,sp]=await Promise.all([schoolApi.getGradeLevels(),schoolApi.getSubjects(),schoolApi.getTeachers(),schoolApi.getClassSections(),getStudentLookups().catch(()=>[]),getUsers().catch(()=>[]),getCourseSupervisorAssignments().catch(()=>({supervisors:[],assignments:[]}))]);const sd=sp||{supervisors:[],assignments:[]};const enriched=arr(s).map(subject=>{const assignment=arr(sd.assignments).find(a=>a.subjectId===subject.id);const ids=arr(assignment?.teacherProfileIds);return {...subject,supervisorIds:ids,supervisorNames:arr(sd.supervisors).filter(x=>ids.includes(x.teacherProfileId)).map(x=>x.name),supervisorOptions:arr(sd.supervisors)}});setGrades(arr(g));setSubjects(enriched);setTeachers(arr(t));setSections(arr(c));setStudents(arr(st));setUsers(arr(u));setSupervisorData(sd);}catch(e){setError(e?.message||"تعذر تحميل بيانات الإدارة التعليمية")}finally{setLoading(false)}}
 useEffect(()=>{loadAll()},[]);
 async function run(action,msg){try{setLoading(true);setError("");setSuccess("");await action();setSuccess(msg);await loadAll();setModal(null)}catch(e){setError(e?.message||"تعذر تنفيذ العملية")}finally{setLoading(false)}}
 const stats={grades:grades.length,subjects:subjects.length,teachers:teachers.length,sections:sections.length};
 const rows=useMemo(()=>{let r=activeTab==="grades"?grades:activeTab==="subjects"?subjects:activeTab==="teachers"?teachers:sections;const q=search.trim().toLowerCase();return q?r.filter(x=>JSON.stringify(x||{}).toLowerCase().includes(q)):r},[activeTab,search,grades,subjects,teachers,sections]);
 async function loadSectionStudents(id){setSelectedSection(id);setStudentSelection([]);if(!id){setSectionStudents([]);return}try{setLoading(true);const data=await schoolApi.getSectionStudents(id);const list=arr(data);setSectionStudents(list);setStudentSelection(list.map(x=>x.studentProfileId||x.id).filter(Boolean))}catch(e){setError(e?.message||"تعذر تحميل طلاب الشعبة")}finally{setLoading(false)}}
 function openCreate(){if(activeTab==="grades")setModal({type:"grade",mode:"create",data:emptyGrade});if(activeTab==="subjects")setModal({type:"subject",mode:"create",data:emptySubject});if(activeTab==="teachers")setModal({type:"teacher",mode:"create",data:emptyTeacher});if(activeTab==="sections")setModal({type:"section",mode:"create",data:emptySection})}
 return <div className="school-page"><div className="school-hero"><div><div className="school-hero-badge">إدارة تعليمية ذكية</div><h1>إدارة المؤسسة التعليمية</h1><p>واجهة موحدة لإدارة المراحل والمقررات والمعلمين والشعب وتسجيل الطلاب بطريقة سهلة ومرتبة.</p></div><button className="school-btn primary" onClick={loadAll}>تحديث البيانات</button></div><div className="school-stats-grid"><Stat t="المراحل" v={stats.grades}/><Stat t="المقررات" v={stats.subjects}/><Stat t="المعلمون" v={stats.teachers}/><Stat t="الشعب" v={stats.sections}/></div>{error&&<div className="school-alert error">{error}</div>}{success&&<div className="school-alert success">{success}</div>}<div className="school-tabs">{tabs.map(t=><button key={t.key} className={activeTab===t.key?"school-tab active":"school-tab"} onClick={()=>{setActiveTab(t.key);setSearch("")}}>{t.icon} {t.label}</button>)}</div>{activeTab!=="students"?<div className="school-panel"><div className="school-panel-head"><div className="school-panel-title"><h2>{tabs.find(x=>x.key===activeTab)?.label}</h2><p>إدارة سهلة وسريعة مع بطاقات واضحة وإجراءات مباشرة.</p></div></div><div className="school-toolbar"><input className="school-input school-search" placeholder="بحث سريع..." value={search} onChange={e=>setSearch(e.target.value)}/><button className="school-btn primary" onClick={openCreate}>إضافة جديد</button><button className="school-btn secondary" onClick={loadAll}>تحديث</button></div>{activeTab==="grades"&&<Grades rows={rows} subjects={subjects} sections={sections} setModal={setModal} run={run}/>} {activeTab==="subjects"&&<Subjects rows={rows} grades={grades} sections={sections} setModal={setModal} run={run}/>} {activeTab==="teachers"&&<Teachers rows={rows} sections={sections} subjects={subjects} setModal={setModal} run={run}/>} {activeTab==="sections"&&<Sections rows={rows} grades={grades} subjects={subjects} teachers={teachers} setModal={setModal} setActiveTab={setActiveTab} loadSectionStudents={loadSectionStudents} run={run}/>}</div>:<SectionStudents sections={sections} subjects={subjects} grades={grades} students={students} selectedSection={selectedSection} loadSectionStudents={loadSectionStudents} studentSelection={studentSelection} setStudentSelection={setStudentSelection} sectionStudents={sectionStudents} run={run}/>} {loading&&<div className="school-alert success">جاري المعالجة...</div>}{modal&&<Editor modal={modal} setModal={setModal} grades={grades} subjects={subjects} teachers={teachers} users={users} run={run}/>}</div>
}
function Stat({t,v}){return <div className="school-stat-card"><span>{t}</span><strong>{v}</strong></div>}
function Grades({rows,subjects,sections,setModal,run}){return <Grid rows={rows} empty="لا توجد مراحل دراسية بعد" render={g=><div className="school-card" key={g.id}><div className="school-card-head"><div><h3>{g.name}</h3><p>ترتيب المرحلة: {g.order??"-"}</p></div><span className={g.isActive?"school-pill green":"school-pill red"}>{g.isActive?"نشط":"معطل"}</span></div><div className="school-meta"><span className="school-pill">مقررات: {subjects.filter(s=>s.gradeLevelId===g.id).length}</span><span className="school-pill">شعب: {sections.filter(s=>s.gradeLevelId===g.id).length}</span></div><Actions onEdit={()=>setModal({type:"grade",mode:"edit",id:g.id,data:{name:g.name||"",order:g.order||1,isActive:g.isActive!==false}})} onStatus={()=>run(()=>schoolApi.setGradeLevelStatus(g.id,!g.isActive),"تم تحديث حالة المرحلة")} onDelete={()=>confirm("هل تريد حذف المرحلة؟")&&run(()=>schoolApi.deleteGradeLevel(g.id),"تم حذف المرحلة")}/></div>}/>}
function Subjects({rows,grades,sections,setModal,run}){return <Grid rows={rows} empty="لا توجد مقررات بعد" render={s=><div className="school-card" key={s.id}><div className="school-card-head"><div><h3>{s.name}</h3><p>{s.code?`كود: ${s.code}`:"بدون كود"}</p></div><span className={s.isActive?"school-pill green":"school-pill red"}>{s.isActive?"نشط":"معطل"}</span></div><div className="school-meta"><span className="school-pill">{byId(grades,s.gradeLevelId)?.name||"مرحلة غير محددة"}</span><span className="school-pill">شعب: {sections.filter(x=>x.subjectId===s.id).length}</span><span className={(s.supervisorNames||[]).length?"school-pill green":"school-pill red"}>{(s.supervisorNames||[]).length?`المشرفون: ${s.supervisorNames.join("، ")}`:"لا يوجد مشرف مقرر"}</span></div><Actions extra={<button className="school-btn primary" onClick={()=>setModal({type:"subjectSupervisors",mode:"edit",id:s.id,name:s.name,options:s.supervisorOptions||[],data:{teacherProfileIds:s.supervisorIds||[]}})}>إدارة المشرفين</button>} onEdit={()=>setModal({type:"subject",mode:"edit",id:s.id,data:{gradeLevelId:s.gradeLevelId||"",name:s.name||"",code:s.code||"",isActive:s.isActive!==false}})} onStatus={()=>run(()=>schoolApi.setSubjectStatus(s.id,!s.isActive),"تم تحديث حالة المقرر")} onDelete={()=>confirm("هل تريد حذف المقرر؟")&&run(()=>schoolApi.deleteSubject(s.id),"تم حذف المقرر")}/></div>}/>}
function Teachers({rows,sections,subjects,setModal,run}){return <Grid rows={rows} empty="لا يوجد معلمون بعد" render={t=><div className="school-card" key={t.id}><div className="school-card-head"><div><h3>{t.fullName}</h3><p>{t.email||t.phoneNumber||"بيانات تواصل غير محددة"}</p></div><span className={t.isActive?"school-pill green":"school-pill red"}>{t.isActive?"نشط":"معطل"}</span></div><div className="school-meta"><span className="school-pill">كود: {t.teacherCode||"-"}</span><span className="school-pill">شعب: {sections.filter(s=>s.teacherProfileId===t.id).length}</span></div><Actions extra={<button className="school-btn soft" onClick={()=>setModal({type:"teacherSubjects",mode:"edit",id:t.id,data:{subjectIds:arr(t.subjectIds||t.subjects?.map(x=>x.id))}})}>المقررات</button>} onEdit={()=>setModal({type:"teacher",mode:"edit",id:t.id,data:{userId:t.userId||"",fullName:t.fullName||"",phoneNumber:t.phoneNumber||"",email:t.email||"",teacherCode:t.teacherCode||"",isActive:t.isActive!==false,subjectIds:arr(t.subjectIds||t.subjects?.map(x=>x.id))}})} onStatus={()=>run(()=>schoolApi.setTeacherStatus(t.id,!t.isActive),"تم تحديث حالة المعلم")} onDelete={()=>confirm("هل تريد حذف المعلم؟")&&run(()=>schoolApi.deleteTeacher(t.id),"تم حذف المعلم")}/></div>}/>}
function Sections({rows,grades,subjects,teachers,setModal,setActiveTab,loadSectionStudents,run}){return <Grid rows={rows} empty="لا توجد شعب دراسية بعد" render={s=><div className="school-card" key={s.id}><div className="school-card-head"><div><h3>{s.name}</h3><p>{byId(subjects,s.subjectId)?.name||"مقرر"} - {byId(grades,s.gradeLevelId)?.name||"مرحلة"}</p></div><span className={s.isActive?"school-pill green":"school-pill red"}>{s.isActive?"نشط":"معطل"}</span></div><div className="school-meta"><span className="school-pill">{byId(teachers,s.teacherProfileId)?.fullName||"بدون معلم"}</span><span className="school-pill">{s.genderType||"Mixed"}</span><span className="school-pill">السعة: {s.capacity??"-"}</span></div><Actions extra={<button className="school-btn soft" onClick={()=>{setActiveTab("students");loadSectionStudents(s.id)}}>الطلاب</button>} onEdit={()=>setModal({type:"section",mode:"edit",id:s.id,data:{gradeLevelId:s.gradeLevelId||"",subjectId:s.subjectId||"",teacherProfileId:s.teacherProfileId||"",name:s.name||"",genderType:s.genderType||"Mixed",academicYear:s.academicYear||"",term:s.term||"",capacity:s.capacity||"",isActive:s.isActive!==false}})} onStatus={()=>run(()=>schoolApi.setClassSectionStatus(s.id,!s.isActive),"تم تحديث حالة الشعبة")} onDelete={()=>confirm("هل تريد حذف الشعبة؟")&&run(()=>schoolApi.deleteClassSection(s.id),"تم حذف الشعبة")}/></div>}/>}
function SectionStudents({sections,subjects,grades,students,selectedSection,loadSectionStudents,studentSelection,setStudentSelection,sectionStudents,run}){const set=new Set(studentSelection);return <div className="school-panel"><div className="school-panel-head"><div className="school-panel-title"><h2>تسجيل الطلاب في الشعب</h2><p>اختر الشعبة ثم حدد الطلاب المطلوب تسجيلهم.</p></div></div><div className="school-form-grid"><div className="school-form-field full"><label>الشعبة الدراسية</label><select className="school-select" value={selectedSection} onChange={e=>loadSectionStudents(e.target.value)}><option value="">اختر الشعبة</option>{sections.map(s=><option key={s.id} value={s.id}>{s.name} - {byId(subjects,s.subjectId)?.name||"مقرر"} - {byId(grades,s.gradeLevelId)?.name||"مرحلة"}</option>)}</select></div>{selectedSection&&<div className="school-form-field full"><label>الطلاب</label><div className="school-students-list">{students.map(st=>{const id=st.id||st.studentProfileId;return <label className="school-check-row" key={id}><input type="checkbox" checked={set.has(id)} onChange={e=>setStudentSelection(prev=>e.target.checked?Array.from(new Set([...prev,id])):prev.filter(x=>x!==id))}/><span>{st.fullName||st.name||st.studentName||"طالب"} {st.studentCode||st.code?`- ${st.studentCode||st.code}`:""}</span></label>})}</div><div className="school-card-actions"><button className="school-btn primary" onClick={()=>run(()=>schoolApi.assignSectionStudents(selectedSection,studentSelection,true),"تم حفظ طلاب الشعبة")}>حفظ واستبدال القائمة</button><button className="school-btn secondary" onClick={()=>run(()=>schoolApi.assignSectionStudents(selectedSection,studentSelection,false),"تمت إضافة الطلاب المحددين")}>إضافة فقط</button></div></div>}</div>{selectedSection&&sectionStudents.length>0&&<div style={{marginTop:16}}><h3>الطلاب المسجلون حاليًا</h3><Grid rows={sectionStudents} empty="" render={r=>{const id=r.studentProfileId||r.id;return <div className="school-card" key={id}><h3>{r.studentName||r.fullName||r.name||"طالب"}</h3><p>{r.studentCode||r.code||""}</p><button className="school-btn danger" onClick={()=>confirm("حذف الطالب من الشعبة؟")&&run(()=>schoolApi.removeSectionStudent(selectedSection,id),"تم حذف الطالب من الشعبة")}>حذف من الشعبة</button></div>}}/></div>}</div>}
function Editor({modal,setModal,grades,subjects,teachers,users,run}){const [form,setForm]=useState(modal.data);const close=()=>setModal(null);if(modal.type==="grade")return <Modal title={modal.mode==="edit"?"تعديل مرحلة":"إضافة مرحلة"} subtitle="نظّم المراحل الدراسية داخل المؤسسة." onClose={close}><form className="school-form-grid" onSubmit={e=>{e.preventDefault();run(()=>modal.mode==="edit"?schoolApi.updateGradeLevel(modal.id,{...form,order:Number(form.order||1)}):schoolApi.createGradeLevel({...form,order:Number(form.order||1)}),modal.mode==="edit"?"تم تحديث المرحلة":"تمت إضافة المرحلة")}}><Field label="اسم المرحلة"><input className="school-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="الترتيب"><input className="school-input" type="number" value={form.order} onChange={e=>setForm({...form,order:e.target.value})}/></Field><ActiveField form={form} setForm={setForm}/><SaveActions mode={modal.mode} onClose={close}/></form></Modal>;
if(modal.type==="subject")return <Modal title={modal.mode==="edit"?"تعديل مقرر":"إضافة مقرر"} subtitle="اربط كل مقرر بالمرحلة المناسبة." onClose={close}><form className="school-form-grid" onSubmit={e=>{e.preventDefault();run(()=>modal.mode==="edit"?schoolApi.updateSubject(modal.id,{...form,gradeLevelId:norm(form.gradeLevelId)}):schoolApi.createSubject({...form,gradeLevelId:norm(form.gradeLevelId)}),modal.mode==="edit"?"تم تحديث المقرر":"تمت إضافة المقرر")}}><Field label="المرحلة"><select className="school-select" value={form.gradeLevelId} onChange={e=>setForm({...form,gradeLevelId:e.target.value})} required><option value="">اختر المرحلة</option>{grades.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="اسم المقرر"><input className="school-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="كود المقرر"><input className="school-input" value={form.code} onChange={e=>setForm({...form,code:e.target.value})}/></Field><ActiveField form={form} setForm={setForm}/><SaveActions mode={modal.mode} onClose={close}/></form></Modal>;
if(modal.type==="subjectSupervisors")return <SupervisorPicker subjectName={modal.name} initial={form.teacherProfileIds||[]} supervisors={modal.options||[]} onClose={close} onSave={ids=>run(()=>setCourseSupervisors(modal.id,ids),"تم تحديث مشرفي المقرر")}/>;
if(modal.type==="teacherSubjects")return <SubjectPicker title="مقررات المعلم" initial={form.subjectIds||[]} subjects={subjects} onClose={close} onSave={ids=>run(()=>schoolApi.assignTeacherSubjects(modal.id,ids),"تم تحديث مقررات المعلم")}/>;
if(modal.type==="teacher")return <TeacherEditor modal={modal} form={form} setForm={setForm} users={users} subjects={subjects} run={run} close={close}/>;
if(modal.type==="section")return <SectionEditor modal={modal} form={form} setForm={setForm} grades={grades} subjects={subjects} teachers={teachers} run={run} close={close}/>;return null}
function SubjectPicker({title,initial,subjects,onClose,onSave}){const [ids,setIds]=useState(initial);return <Modal title={title} subtitle="حدد المقررات المطلوبة." onClose={onClose}><div className="school-students-list">{subjects.map(s=><label className="school-check-row" key={s.id}><input type="checkbox" checked={ids.includes(s.id)} onChange={()=>setIds(p=>p.includes(s.id)?p.filter(x=>x!==s.id):[...p,s.id])}/><span>{s.name} {s.code?`- ${s.code}`:""}</span></label>)}</div><div className="school-card-actions"><button className="school-btn primary" onClick={()=>onSave(ids)}>حفظ</button><button className="school-btn soft" onClick={onClose}>إلغاء</button></div></Modal>}
function SupervisorPicker({subjectName,initial,supervisors,onClose,onSave}){const [ids,setIds]=useState(initial);return <Modal title={`مشرفو مقرر: ${subjectName}`} subtitle="يمكن اختيار مشرف واحد أو أكثر. إلغاء التحديد يفك ارتباط المشرف بالمقرر." onClose={onClose}>{!supervisors.length?<div className="school-empty">لا توجد حسابات فعالة بصلاحية مشرف مقرر. أنشئ الحساب أولاً من إدارة المستخدمين واربطه بملف معلم.</div>:<div className="school-students-list">{supervisors.map(s=><label className="school-check-row" key={s.teacherProfileId}><input type="checkbox" checked={ids.includes(s.teacherProfileId)} onChange={()=>setIds(p=>p.includes(s.teacherProfileId)?p.filter(x=>x!==s.teacherProfileId):[...p,s.teacherProfileId])}/><span><strong>{s.name}</strong> — {s.userName}</span></label>)}</div>}<div className="school-card-actions"><button className="school-btn primary" disabled={!supervisors.length} onClick={()=>onSave(ids)}>حفظ المشرفين</button><button className="school-btn soft" onClick={onClose}>إلغاء</button></div></Modal>}
function TeacherEditor({modal,form,setForm,users,subjects,run,close}){const teacherUsers=arr(users).filter(u=>String(u.role||"").toLowerCase()==="teacher");const toggle=id=>setForm(p=>({...p,subjectIds:p.subjectIds?.includes(id)?p.subjectIds.filter(x=>x!==id):[...(p.subjectIds||[]),id]}));return <Modal title={modal.mode==="edit"?"تعديل معلم":"إضافة معلم"} subtitle="أضف بيانات المعلم واربطه بالمقررات." onClose={close}><form className="school-form-grid" onSubmit={e=>{e.preventDefault();run(()=>modal.mode==="edit"?schoolApi.updateTeacher(modal.id,{...form,userId:norm(form.userId)}):schoolApi.createTeacher({...form,userId:norm(form.userId)}),modal.mode==="edit"?"تم تحديث المعلم":"تمت إضافة المعلم")}}><Field label="ربط بحساب مستخدم Teacher"><select className="school-select" value={form.userId} onChange={e=>setForm({...form,userId:e.target.value})}><option value="">بدون ربط الآن</option>{teacherUsers.map(u=><option key={u.id} value={u.id}>{u.userName}</option>)}</select></Field><Field label="اسم المعلم"><input className="school-input" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} required/></Field><Field label="رقم الجوال"><input className="school-input" value={form.phoneNumber} onChange={e=>setForm({...form,phoneNumber:e.target.value})}/></Field><Field label="البريد الإلكتروني"><input className="school-input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></Field><Field label="كود المعلم"><input className="school-input" value={form.teacherCode} onChange={e=>setForm({...form,teacherCode:e.target.value})}/></Field><ActiveField form={form} setForm={setForm}/><div className="school-form-field full"><label>المقررات المرتبطة</label><div className="school-students-list">{subjects.map(s=><label className="school-check-row" key={s.id}><input type="checkbox" checked={(form.subjectIds||[]).includes(s.id)} onChange={()=>toggle(s.id)}/><span>{s.name}</span></label>)}</div></div><SaveActions mode={modal.mode} onClose={close}/></form></Modal>}
function SectionEditor({modal,form,setForm,grades,subjects,teachers,run,close}){const filtered=form.gradeLevelId?subjects.filter(s=>s.gradeLevelId===form.gradeLevelId):subjects;return <Modal title={modal.mode==="edit"?"تعديل شعبة":"إضافة شعبة"} subtitle="أنشئ شعبة مرتبطة بمرحلة ومقرر ومعلم." onClose={close}><form className="school-form-grid" onSubmit={e=>{e.preventDefault();const payload={...form,gradeLevelId:norm(form.gradeLevelId),subjectId:norm(form.subjectId),teacherProfileId:norm(form.teacherProfileId),capacity:form.capacity===""?null:Number(form.capacity)};run(()=>modal.mode==="edit"?schoolApi.updateClassSection(modal.id,payload):schoolApi.createClassSection(payload),modal.mode==="edit"?"تم تحديث الشعبة":"تمت إضافة الشعبة")}}><Field label="المرحلة"><select className="school-select" value={form.gradeLevelId} onChange={e=>setForm({...form,gradeLevelId:e.target.value,subjectId:""})} required><option value="">اختر المرحلة</option>{grades.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></Field><Field label="المقرر"><select className="school-select" value={form.subjectId} onChange={e=>setForm({...form,subjectId:e.target.value})} required><option value="">اختر المقرر</option>{filtered.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="المعلم"><select className="school-select" value={form.teacherProfileId} onChange={e=>setForm({...form,teacherProfileId:e.target.value})}><option value="">بدون معلم</option>{teachers.map(t=><option key={t.id} value={t.id}>{t.fullName}</option>)}</select></Field><Field label="اسم الشعبة"><input className="school-input" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></Field><Field label="نوع الشعبة"><select className="school-select" value={form.genderType} onChange={e=>setForm({...form,genderType:e.target.value})}><option value="Male">طلاب</option><option value="Female">طالبات</option><option value="Mixed">مختلط</option></select></Field><Field label="العام الدراسي"><input className="school-input" value={form.academicYear} onChange={e=>setForm({...form,academicYear:e.target.value})} placeholder="2025/2026"/></Field><Field label="الفصل الدراسي"><input className="school-input" value={form.term} onChange={e=>setForm({...form,term:e.target.value})} placeholder="الأول"/></Field><Field label="السعة"><input className="school-input" type="number" value={form.capacity} onChange={e=>setForm({...form,capacity:e.target.value})}/></Field><ActiveField form={form} setForm={setForm}/><SaveActions mode={modal.mode} onClose={close}/></form></Modal>}
