// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizSystem.Infrastructure.Persistence;

#nullable disable

namespace QuizSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260815081233_AddCloAssessmentAndMultipleAttempts")]
    partial class AddCloAssessmentAndMultipleAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuizSystem.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerificationTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailVerificationTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EmailVerifiedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeacherProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("InstitutionId");

                    b.HasIndex("ParentProfileId")
                        .IsUnique();

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("TeacherProfileId")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("ExamQuestionId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("AttemptAnswers", (string)null);
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ClassSection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AcademicYear")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("GenderType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeacherProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Term")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.ToTable("ClassSections");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.CourseLearningOutcome", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CognitiveLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Domain")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TargetPercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("InstitutionId", "SubjectId", "Code")
                        .IsUnique();

                    b.ToTable("CourseLearningOutcomes");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowStudentExit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssessmentType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClassSectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedManually")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAntiCheat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxViolationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TeacherProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("InstitutionId", "ExamCode")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ClassSectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Percentage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("ExamId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("InstitutionId", "ExamId", "StudentProfileId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("Attempts", (string)null);
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptDraftAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("ExamAttemptDraftAnswers");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptQuestionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceADisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOriginalKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("ExamAttemptQuestionSnapshots");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("ExamAttemptViolations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("CognitiveLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CourseLearningOutcomeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseLearningOutcomeId");

                    b.HasIndex("ExamId");

                    b.HasIndex("InstitutionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ClassSectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("ExamId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("InstitutionId", "ExamId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.GradeLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.ToTable("GradeLevels");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Institution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamManagementMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Institutions");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("InstitutionId", "ParentCode")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentStudentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentProfileId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("InstitutionId", "ParentProfileId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("ParentStudentLinks");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReplacedByTokenHash")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.SectionStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClassSectionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClassSectionId");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("InstitutionId", "ClassSectionId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("SectionStudents");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Branch")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("GradeLevelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImagePath")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("InstitutionId", "StudentCode")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GradeLevelId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GradeLevelId");

                    b.HasIndex("InstitutionId", "Code")
                        .IsUnique();

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.TeacherProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId", "TeacherCode")
                        .IsUnique();

                    b.ToTable("TeacherProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.TeacherSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InstitutionId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeacherProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InstitutionId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherProfileId");

                    b.HasIndex("InstitutionId", "TeacherProfileId", "SubjectId")
                        .IsUnique();

                    b.ToTable("TeacherSubjects");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("Users")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizSystem.Domain.Entities.ParentProfile", "ParentProfile")
                        .WithOne("User")
                        .HasForeignKey("QuizSystem.Domain.Entities.AppUser", "ParentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizSystem.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithOne("User")
                        .HasForeignKey("QuizSystem.Domain.Entities.AppUser", "TeacherProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Institution");

                    b.Navigation("ParentProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("ExamQuestion");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ClassSection", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("ClassSections")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("ClassSections")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Subject", "Subject")
                        .WithMany("ClassSections")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany("ClassSections")
                        .HasForeignKey("TeacherProfileId");

                    b.Navigation("GradeLevel");

                    b.Navigation("Institution");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.CourseLearningOutcome", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Exam", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany()
                        .HasForeignKey("ClassSectionId");

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("QuizSystem.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany()
                        .HasForeignKey("TeacherProfileId");

                    b.Navigation("ClassSection");

                    b.Navigation("Institution");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany()
                        .HasForeignKey("ClassSectionId");

                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Exam");

                    b.Navigation("Institution");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptDraftAnswer", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("DraftAnswers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptQuestionSnapshot", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("QuestionSnapshots")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptViolation", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("Violations")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.CourseLearningOutcome", "CourseLearningOutcome")
                        .WithMany()
                        .HasForeignKey("CourseLearningOutcomeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseLearningOutcome");

                    b.Navigation("Exam");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamRegistration", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany()
                        .HasForeignKey("ClassSectionId");

                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Registrations")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ExamRegistrations")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Exam");

                    b.Navigation("Institution");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.GradeLevel", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("GradeLevels")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentProfile", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("Parents")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentStudentLink", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.ParentProfile", "ParentProfile")
                        .WithMany("ParentStudentLinks")
                        .HasForeignKey("ParentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ParentLinks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("ParentProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.SectionStudent", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ClassSection", "ClassSection")
                        .WithMany("SectionStudents")
                        .HasForeignKey("ClassSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("SectionStudents")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSection");

                    b.Navigation("Institution");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany()
                        .HasForeignKey("GradeLevelId");

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("Students")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Subject", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.GradeLevel", "GradeLevel")
                        .WithMany("Subjects")
                        .HasForeignKey("GradeLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("Subjects")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GradeLevel");

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.TeacherProfile", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany("Teachers")
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.TeacherSubject", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Institution", "Institution")
                        .WithMany()
                        .HasForeignKey("InstitutionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.TeacherProfile", "TeacherProfile")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Institution");

                    b.Navigation("Subject");

                    b.Navigation("TeacherProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ClassSection", b =>
                {
                    b.Navigation("SectionStudents");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("DraftAnswers");

                    b.Navigation("QuestionSnapshots");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.GradeLevel", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Institution", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("GradeLevels");

                    b.Navigation("Parents");

                    b.Navigation("Students");

                    b.Navigation("Subjects");

                    b.Navigation("Teachers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentProfile", b =>
                {
                    b.Navigation("ParentStudentLinks");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("ExamRegistrations");

                    b.Navigation("ParentLinks");

                    b.Navigation("SectionStudents");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Subject", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.TeacherProfile", b =>
                {
                    b.Navigation("ClassSections");

                    b.Navigation("TeacherSubjects");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
