// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuizSystem.Infrastructure.Persistence;

#nullable disable

namespace QuizSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503185330_SyncCurrentModel")]
    partial class SyncCurrentModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("QuizSystem.Domain.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentProfileId")
                        .IsUnique();

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.HasIndex("ExamQuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowStudentExit")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BankQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("CreatedManually")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EnableAntiCheat")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExamCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ExamQuestionCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxViolationCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamCode")
                        .IsUnique();

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Percentage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SubmittedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("ExamId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptDraftAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SavedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("ExamAttemptDraftAnswers");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptQuestionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceADisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDDisplayLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectOriginalKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OriginalQuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedOriginalKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("ExamAttemptQuestionSnapshots");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptViolation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamAttemptId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamAttemptId");

                    b.ToTable("ExamAttemptViolations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceA")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceAImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceB")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceBImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceC")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceCImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceD")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChoiceDImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("ExamId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentCode")
                        .IsUnique();

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentStudentLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ParentProfileId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StudentProfileId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentProfileId");

                    b.HasIndex("ParentProfileId", "StudentProfileId")
                        .IsUnique();

                    b.ToTable("ParentStudentLinks");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StudentCode")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ParentProfile", "ParentProfile")
                        .WithOne("User")
                        .HasForeignKey("QuizSystem.Domain.Entities.AppUser", "ParentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany()
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.AttemptAnswer", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("Answers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.ExamQuestion", "ExamQuestion")
                        .WithMany()
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Attempts")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ExamAttempts")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptDraftAnswer", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("DraftAnswers")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptQuestionSnapshot", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("QuestionSnapshots")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttemptViolation", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ExamAttempt", "ExamAttempt")
                        .WithMany("Violations")
                        .HasForeignKey("ExamAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExamAttempt");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamQuestion", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamRegistration", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.Exam", "Exam")
                        .WithMany("Registrations")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ExamRegistrations")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exam");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentStudentLink", b =>
                {
                    b.HasOne("QuizSystem.Domain.Entities.ParentProfile", "ParentProfile")
                        .WithMany("ParentStudentLinks")
                        .HasForeignKey("ParentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuizSystem.Domain.Entities.StudentProfile", "StudentProfile")
                        .WithMany("ParentLinks")
                        .HasForeignKey("StudentProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentProfile");

                    b.Navigation("StudentProfile");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.Exam", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Questions");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ExamAttempt", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("DraftAnswers");

                    b.Navigation("QuestionSnapshots");

                    b.Navigation("Violations");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.ParentProfile", b =>
                {
                    b.Navigation("ParentStudentLinks");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QuizSystem.Domain.Entities.StudentProfile", b =>
                {
                    b.Navigation("ExamAttempts");

                    b.Navigation("ExamRegistrations");

                    b.Navigation("ParentLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
