import { useEffect, useState } from "react";
import { createCourseClo, deleteCourseClo, getCourseCloReport, getCourseClos, getAssignedCourses, getReadableErrorMessage, importCourseClos } from "../../services/api";
import PageIntro from "../../components/ui/PageIntro";
import SectionCard from "../../components/ui/SectionCard";

const empty = { code: "", description: "", domain: "Knowledge", cognitiveLevel: "Understand", targetPercentage: 70, displayOrder: 1, isActive: true };
export default function CourseOutcomesPage() {
  const [subjects,setSubjects]=useState([]), [subjectId,setSubjectId]=useState(""), [rows,setRows]=useState([]), [report,setReport]=useState([]), [form,setForm]=useState(empty), [message,setMessage]=useState("");
  useEffect(()=>{getAssignedCourses().then(x=>setSubjects(Array.isArray(x)?x:[])).catch(e=>setMessage(getReadableErrorMessage(e)));},[]);
  async function load(id=subjectId){if(!id)return;try{const [a,b]=await Promise.all([getCourseClos(id),getCourseCloReport(id)]);setRows(a||[]);setReport(b||[]);}catch(e){setMessage(getReadableErrorMessage(e));}}
  async function save(e){e.preventDefault();try{await createCourseClo(subjectId,form);setForm(empty);setMessage("تم حفظ مخرج التعلم");await load();}catch(x){setMessage(getReadableErrorMessage(x));}}
  async function upload(e){const file=e.target.files?.[0];if(!file)return;try{const x=await importCourseClos(subjectId,file);setMessage(`تمت إضافة ${x.added} وتحديث ${x.updated}`);await load();}catch(x){setMessage(getReadableErrorMessage(x));}e.target.value="";}
  return <div><PageIntro title="مخرجات تعلم المقرر (CLO)" description="صياغة مخرجات قابلة للقياس وربطها بمستويات Bloom ومتابعة تحققها." />{message&&<div className="alert">{message}</div>}
  <SectionCard title="المقرر والاستيراد"><div className="entity-toolbar"><select value={subjectId} onChange={e=>{setSubjectId(e.target.value);load(e.target.value);}}><option value="">اختر المقرر</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select>{subjectId&&<><a className="ghost-btn slim" href="/api/courses/clos/template">تحميل نموذج Excel</a><label className="primary-btn slim">رفع Excel<input hidden type="file" accept=".xlsx" onChange={upload}/></label></>}</div></SectionCard>
  {subjectId&&<><SectionCard title="إضافة مخرج"><form className="entity-form-grid" onSubmit={save}><div className="entity-form-field"><label>الرمز</label><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="CLO1"/></div><div className="entity-form-field"><label>المجال</label><select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}><option value="Knowledge">المعرفة</option><option value="Skills">المهارات</option><option value="Values">القيم</option></select></div><div className="entity-form-field"><label>مستوى Bloom</label><select value={form.cognitiveLevel} onChange={e=>setForm({...form,cognitiveLevel:e.target.value})}>{["Remember","Understand","Apply","Analyze","Evaluate","Create"].map(x=><option key={x}>{x}</option>)}</select></div><div className="entity-form-field"><label>هدف التحقق %</label><input type="number" min="0" max="100" value={form.targetPercentage} onChange={e=>setForm({...form,targetPercentage:Number(e.target.value)})}/></div><div className="entity-form-field entity-form-field-wide"><label>وصف قابل للقياس</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><button className="primary-btn">حفظ CLO</button></form></SectionCard>
  <SectionCard title="المخرجات ونتائج القياس"><div className="table-wrap"><table><thead><tr><th>الرمز</th><th>الوصف</th><th>التصنيف</th><th>الأسئلة</th><th>التحقق</th><th></th></tr></thead><tbody>{rows.map(x=>{const r=report.find(y=>y.id===x.id);return <tr key={x.id}><td>{x.code}</td><td>{x.description}</td><td>{x.domain} / {x.cognitiveLevel}</td><td>{r?.questions||0}</td><td>{r?.attainmentPercentage||0}% (الهدف {x.targetPercentage}%)</td><td><button className="danger-btn slim" onClick={async()=>{if(confirm("حذف المخرج؟")){await deleteCourseClo(subjectId,x.id);load();}}}>حذف</button></td></tr>})}</tbody></table></div></SectionCard></>}
  </div>;
}
