import { useEffect, useState } from "react";
import { approveGeneratedCourseClos, createCourseClo, deleteCourseClo, generateCourseClosFromPdf, getAssignedCourses, getCourseCloReport, getCourseClos, getReadableErrorMessage, importCourseClos } from "../../services/api";
import PageIntro from "../../components/ui/PageIntro";
import SectionCard from "../../components/ui/SectionCard";

const empty = { code: "", description: "", domain: "Knowledge", cognitiveLevel: "Understand", targetPercentage: 70, displayOrder: 1, isActive: true };
const levels = ["Remember", "Understand", "Apply", "Analyze", "Evaluate", "Create"];

export default function CourseOutcomesPage() {
  const [subjects,setSubjects]=useState([]), [subjectId,setSubjectId]=useState(""), [rows,setRows]=useState([]), [report,setReport]=useState([]);
  const [form,setForm]=useState(empty), [message,setMessage]=useState(""), [busy,setBusy]=useState(false), [pdf,setPdf]=useState(null), [count,setCount]=useState(6), [summary,setSummary]=useState(""), [drafts,setDrafts]=useState([]);
  useEffect(()=>{getAssignedCourses().then(x=>setSubjects(Array.isArray(x)?x:[])).catch(e=>setMessage(getReadableErrorMessage(e)));},[]);
  async function load(id=subjectId){if(!id)return;try{const [a,b]=await Promise.all([getCourseClos(id),getCourseCloReport(id)]);setRows(a||[]);setReport(b||[]);}catch(e){setMessage(getReadableErrorMessage(e));}}
  async function save(e){e.preventDefault();try{await createCourseClo(subjectId,form);setForm(empty);setMessage("تم حفظ مخرج التعلم");await load();}catch(x){setMessage(getReadableErrorMessage(x));}}
  async function upload(e){const file=e.target.files?.[0];if(!file)return;try{const x=await importCourseClos(subjectId,file);setMessage(`تمت إضافة ${x.added} وتحديث ${x.updated}`);await load();}catch(x){setMessage(getReadableErrorMessage(x));}e.target.value="";}
  async function generate(){if(!pdf)return setMessage("اختر ملف PDF الخاص بالمقرر أولًا.");setBusy(true);setMessage("");try{const x=await generateCourseClosFromPdf(subjectId,pdf,count);setSummary(x.summary||"");setDrafts((x.clos||[]).map((c,i)=>({...c,selected:true,displayOrder:c.displayOrder||i+1,isActive:true})));setMessage("تم تلخيص الملف وإنشاء مسودة CLO. راجعها ثم اعتمد المناسب.");}catch(e){setMessage(getReadableErrorMessage(e));}finally{setBusy(false);}}
  async function approve(){const accepted=drafts.filter(x=>x.selected).map(({selected,...x})=>x);if(!accepted.length)return setMessage("اختر مخرجًا واحدًا على الأقل للاعتماد.");setBusy(true);try{const x=await approveGeneratedCourseClos(subjectId,accepted,drafts.length-accepted.length);setDrafts([]);setSummary("");setPdf(null);setMessage(`تم اعتماد ${x.added+x.updated} مخرج، ورفض ${x.rejected}.`);await load();}catch(e){setMessage(getReadableErrorMessage(e));}finally{setBusy(false);}}
  const editDraft=(i,key,value)=>setDrafts(drafts.map((x,n)=>n===i?{...x,[key]:value}:x));
  return <div dir="rtl"><PageIntro title="مخرجات تعلم المقرر (CLO)" description="أنشئ مخرجات قابلة للقياس يدويًا أو استخرج مسودة من PDF ثم راجعها واعتمدها." />{message&&<div className="alert">{message}</div>}
    <SectionCard title="المقرر والاستيراد"><div className="entity-toolbar"><select value={subjectId} onChange={e=>{setSubjectId(e.target.value);setDrafts([]);setSummary("");load(e.target.value);}}><option value="">اختر المقرر</option>{subjects.map(x=><option key={x.id} value={x.id}>{x.name} ({x.code})</option>)}</select>{subjectId&&<><a className="ghost-btn slim" href="/api/courses/clos/template">تحميل نموذج Excel</a><label className="primary-btn slim">رفع Excel<input hidden type="file" accept=".xlsx" onChange={upload}/></label></>}</div></SectionCard>
    {subjectId&&<>
      <SectionCard title="وكيل الذكاء الاصطناعي: PDF ← تلخيص ← CLO" subtitle="النتيجة مسودة للمراجعة فقط ولن تُحفظ قبل اعتمادك."><div className="entity-form-grid"><div className="entity-form-field entity-form-field-wide"><label>ملف محتوى المقرر PDF</label><input type="file" accept="application/pdf,.pdf" onChange={e=>setPdf(e.target.files?.[0]||null)}/></div><div className="entity-form-field"><label>عدد المخرجات</label><input type="number" min="1" max="15" value={count} onChange={e=>setCount(Number(e.target.value))}/></div><button type="button" className="primary-btn" disabled={busy} onClick={generate}>{busy?"جاري القراءة والتلخيص...":"تحليل الملف وإنشاء المسودة"}</button></div>
      {summary&&<details style={{marginTop:16}}><summary>عرض ملخص محتوى المقرر</summary><p style={{whiteSpace:"pre-wrap",lineHeight:1.9}}>{summary}</p></details>}
      {!!drafts.length&&<div className="table-wrap" style={{marginTop:18}}><table><thead><tr><th>اعتماد</th><th>الرمز</th><th>المخرج القابل للقياس</th><th>المجال</th><th>Bloom</th><th>الهدف %</th></tr></thead><tbody>{drafts.map((x,i)=><tr key={i}><td><input type="checkbox" checked={x.selected} onChange={e=>editDraft(i,"selected",e.target.checked)}/></td><td><input value={x.code} onChange={e=>editDraft(i,"code",e.target.value)}/></td><td><textarea value={x.description} onChange={e=>editDraft(i,"description",e.target.value)}/></td><td><select value={x.domain} onChange={e=>editDraft(i,"domain",e.target.value)}><option value="Knowledge">معرفة</option><option value="Skills">مهارات</option><option value="Values">قيم</option></select></td><td><select value={x.cognitiveLevel} onChange={e=>editDraft(i,"cognitiveLevel",e.target.value)}>{levels.map(v=><option key={v}>{v}</option>)}</select></td><td><input type="number" min="0" max="100" value={x.targetPercentage} onChange={e=>editDraft(i,"targetPercentage",Number(e.target.value))}/></td></tr>)}</tbody></table><button className="primary-btn" disabled={busy} onClick={approve}>اعتماد المخرجات المحددة</button></div>}</SectionCard>
      <SectionCard title="إضافة مخرج يدويًا"><form className="entity-form-grid" onSubmit={save}><div className="entity-form-field"><label>الرمز</label><input required value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="CLO1"/></div><div className="entity-form-field"><label>المجال</label><select value={form.domain} onChange={e=>setForm({...form,domain:e.target.value})}><option value="Knowledge">المعرفة</option><option value="Skills">المهارات</option><option value="Values">القيم</option></select></div><div className="entity-form-field"><label>مستوى Bloom</label><select value={form.cognitiveLevel} onChange={e=>setForm({...form,cognitiveLevel:e.target.value})}>{levels.map(x=><option key={x}>{x}</option>)}</select></div><div className="entity-form-field"><label>هدف التحقق %</label><input type="number" min="0" max="100" value={form.targetPercentage} onChange={e=>setForm({...form,targetPercentage:Number(e.target.value)})}/></div><div className="entity-form-field entity-form-field-wide"><label>وصف قابل للقياس</label><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><button className="primary-btn">حفظ CLO</button></form></SectionCard>
      <SectionCard title="المخرجات ونتائج القياس"><div className="table-wrap"><table><thead><tr><th>الرمز</th><th>الوصف</th><th>التصنيف</th><th>الأسئلة</th><th>التحقق</th><th></th></tr></thead><tbody>{rows.map(x=>{const r=report.find(y=>y.id===x.id);return <tr key={x.id}><td>{x.code}</td><td>{x.description}</td><td>{x.domain} / {x.cognitiveLevel}</td><td>{r?.questions||0}</td><td>{r?.attainmentPercentage||0}% (الهدف {x.targetPercentage}%)</td><td><button className="danger-btn slim" onClick={async()=>{if(confirm("حذف المخرج؟")){await deleteCourseClo(subjectId,x.id);load();}}}>حذف</button></td></tr>})}</tbody></table></div></SectionCard>
    </>}</div>;
}
